// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abxrphctohxctpmaozvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFieHJwaGN0b2h4Y3RwbWFvenZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MTIyNDgsImV4cCI6MjA2MTM4ODI0OH0.BHT8zdD4IuSrEzybqXxuADFB903FBl0f0C_yC7lSe_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);